version: "3"
services:
  mysql:
    container_name: mydatabase
    image: mysql
    ports:
      - "3308:3306"  # Porta host:porta container
    environment:
      MYSQL_ROOT_PASSWORD: Carlos1218
    volumes:
      - mysql_data:/var/lib/mysql
    command: --innodb-flush-method=fsync

volumes:
  mysql_data:
    driver: local